"""Add admin_reply to escalated queries

Revision ID: 1a09ec0bbaa0
Revises: 268700ddc097
Create Date: 2026-09-14 16:55:03.526856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a09ec0bbaa0'
down_revision: Union[str, None] = '268700ddc097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escalated_queries', sa.Column('admin_reply', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escalated_queries', 'admin_reply')
    # ### end Alembic commands ###
