"""Add escalated queries

Revision ID: 268700ddc097
Revises: e08aa8445251
Create Date: 2026-09-14 16:35:41.413605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268700ddc097'
down_revision: Union[str, None] = 'e08aa8445251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalated_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalated_queries_thread_id'), 'escalated_queries', ['thread_id'], unique=False)
    op.create_index(op.f('ix_escalated_queries_user_id'), 'escalated_queries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escalated_queries_user_id'), table_name='escalated_queries')
    op.drop_index(op.f('ix_escalated_queries_thread_id'), table_name='escalated_queries')
    op.drop_table('escalated_queries')
    # ### end Alembic commands ###
