"""add historical placement tables

Revision ID: e08aa8445251
Revises: 98114df2c8b8
Create Date: 2026-09-14 03:30:42.546573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08aa8445251'
down_revision: Union[str, None] = '98114df2c8b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_drives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('job_role', sa.String(), nullable=False),
    sa.Column('offer_type', sa.String(), nullable=False),
    sa.Column('branches_eligible', sa.String(), nullable=False),
    sa.Column('min_cgpa_required', sa.Float(), nullable=False),
    sa.Column('backlog_allowed', sa.Boolean(), nullable=False),
    sa.Column('bond_years', sa.Integer(), nullable=False),
    sa.Column('job_location', sa.String(), nullable=False),
    sa.Column('selection_rounds', sa.String(), nullable=False),
    sa.Column('visit_month', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('funnel_applied', sa.Integer(), nullable=False),
    sa.Column('funnel_shortlisted', sa.Integer(), nullable=False),
    sa.Column('funnel_interviewed', sa.Integer(), nullable=False),
    sa.Column('funnel_selected', sa.Integer(), nullable=False),
    sa.Column('ctc_offered_lpa', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_drives_academic_year'), 'historical_drives', ['academic_year'], unique=False)
    op.create_index(op.f('ix_historical_drives_branch'), 'historical_drives', ['branch'], unique=False)
    op.create_index(op.f('ix_historical_drives_company_name'), 'historical_drives', ['company_name'], unique=False)
    op.create_index(op.f('ix_historical_drives_id'), 'historical_drives', ['id'], unique=False)
    op.create_table('historical_student_outcomes',
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('had_backlogs', sa.Boolean(), nullable=False),
    sa.Column('placed', sa.Boolean(), nullable=False),
    sa.Column('total_offers_received', sa.Integer(), nullable=False),
    sa.Column('highest_ctc_lpa', sa.Float(), nullable=False),
    sa.Column('company_joined', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_historical_student_outcomes_academic_year'), 'historical_student_outcomes', ['academic_year'], unique=False)
    op.create_index(op.f('ix_historical_student_outcomes_branch'), 'historical_student_outcomes', ['branch'], unique=False)
    op.create_table('yearly_batch_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('total_placed', sa.Integer(), nullable=False),
    sa.Column('total_unplaced', sa.Integer(), nullable=False),
    sa.Column('placement_percentage', sa.Float(), nullable=False),
    sa.Column('highest_ctc_lpa', sa.Float(), nullable=False),
    sa.Column('average_ctc_lpa', sa.Float(), nullable=False),
    sa.Column('median_ctc_lpa', sa.Float(), nullable=False),
    sa.Column('total_companies_visited', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yearly_batch_summary_academic_year'), 'yearly_batch_summary', ['academic_year'], unique=False)
    op.create_index(op.f('ix_yearly_batch_summary_branch'), 'yearly_batch_summary', ['branch'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yearly_batch_summary_branch'), table_name='yearly_batch_summary')
    op.drop_index(op.f('ix_yearly_batch_summary_academic_year'), table_name='yearly_batch_summary')
    op.drop_table('yearly_batch_summary')
    op.drop_index(op.f('ix_historical_student_outcomes_branch'), table_name='historical_student_outcomes')
    op.drop_index(op.f('ix_historical_student_outcomes_academic_year'), table_name='historical_student_outcomes')
    op.drop_table('historical_student_outcomes')
    op.drop_index(op.f('ix_historical_drives_id'), table_name='historical_drives')
    op.drop_index(op.f('ix_historical_drives_company_name'), table_name='historical_drives')
    op.drop_index(op.f('ix_historical_drives_branch'), table_name='historical_drives')
    op.drop_index(op.f('ix_historical_drives_academic_year'), table_name='historical_drives')
    op.drop_table('historical_drives')
    # ### end Alembic commands ###
